# Generated by Django 3.0.7 on 2020-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_auto_20200626_1101'),
        ('users', '0003_auto_20200626_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exchange',
            field=models.ManyToManyField(blank=True, default=None, to='exchanges.Exchange'),
        ),
    ]
