# Generated by Django 3.0.7 on 2020-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_auto_20200626_1108'),
        ('users', '0004_auto_20200626_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exchange',
            field=models.ManyToManyField(default=None, null=True, to='exchanges.Exchange'),
        ),
    ]
