# Generated by Django 3.0.7 on 2020-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0011_auto_20200626_1114'),
        ('users', '0005_auto_20200626_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exchange',
            field=models.ManyToManyField(blank=True, default=None, to='exchanges.Exchange'),
        ),
    ]
