# Generated by Django 3.0.7 on 2020-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0020_auto_20200628_1013'),
        ('users', '0006_auto_20200626_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exchange_history',
            field=models.ManyToManyField(blank=True, default=None, to='exchanges.ExchangeData'),
        ),
    ]
