# Generated by Django 3.0.7 on 2020-06-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_exchange_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exchange_history',
            new_name='exchanges_history',
        ),
    ]
