# Generated by Django 3.0.7 on 2020-06-26 10:36

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 26, 10, 36, 14, 597081))),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pnl_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('pnl_percent_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('typeExchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.ExchangeType')),
            ],
        ),
    ]
