# Generated by Django 3.0.7 on 2020-06-26 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_auto_20200626_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 10, 46, 59, 443130)),
        ),
    ]
