# Generated by Django 3.0.7 on 2020-06-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0008_auto_20200626_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 11, 1, 4, 39518)),
        ),
    ]
