# Generated by Django 3.0.7 on 2020-06-26 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_auto_20200626_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 11, 14, 33, 533081)),
        ),
    ]
