# Generated by Django 3.0.7 on 2020-06-26 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0012_auto_20200626_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='secret_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 11, 34, 37, 845545)),
        ),
    ]
