# Generated by Django 3.0.7 on 2020-06-27 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0013_auto_20200626_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='typeAccount',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 5, 41, 57, 920922)),
        ),
    ]
