# Generated by Django 3.0.7 on 2020-06-27 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0014_auto_20200627_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='typeAccount',
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 5, 46, 58, 855628)),
        ),
    ]
